blueprint:
  name: Linked Entities (fork)
  description: >-

    2
  domain: automation
  input:
    linked_entity:
      name: Linked Entities
      description: Entities whose state and attributes will be linked (if any of them transitions to ON state, all will be ON. Same for the OFF, BRIGHTNESS, COLOR_TEMP, and SPEED states).
      selector:
        entity:
          multiple: true

mode: single
max_exceeded: silent

variables:
  linked_entities: !input linked_entity
  
trigger:
  - platform: state
    id: turn_on
    entity_id: !input linked_entity
    from: "off"
    to: "on"
  - platform: state
    id: turn_off
    entity_id: !input linked_entity
    from: "on"
    to: "off"
  - platform: state
    id: set_speed
    entity_id: !input linked_entity
    attribute: percentage
  - platform: state
    id: set_brightness
    entity_id: !input linked_entity
    attribute: brightness
  - platform: state
    id: set_color_temp
    entity_id: !input linked_entity
    attribute: color_temp
    
condition:
- condition: template
  value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
- condition: template
  value_template: '{{trigger.to_state.context.parent_id is none or trigger.from_state.context.parent_id is none }}'

action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - service: "homeassistant.turn_on"
            target:
              entity_id: !input linked_entity
          - delay:
              milliseconds: 200
      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - service: "homeassistant.turn_off"
            target:
              entity_id: !input linked_entity
          - delay:
              milliseconds: 200
      - conditions:
          - condition: trigger
            id: set_speed
        sequence:
          - variables:
              set_fan_speed: "{{ trigger.to_state.attributes.percentage }}"
          - service: fan.set_percentage
            data:
              entity_id: !input linked_entity
              percentage: "{{ set_fan_speed }}"
          - delay:
              milliseconds: 200
      - conditions:
          - condition: trigger
            id: set_brightness
        sequence:
          - variables:
              set_light_brightness: "{{ trigger.to_state.attributes.brightness }}"
          - service: light.turn_on
            data:
              entity_id: !input linked_entity
              brightness: "{{ set_light_brightness }}"
          - delay:
              milliseconds: 200
      - conditions:
          - condition: trigger
            id: set_color_temp
        sequence:
          - variables:
              set_light_color_temp: "{{ trigger.to_state.attributes.color_temp }}"
          - service: light.turn_on
            data:
              entity_id: !input linked_entity
              color_temp: "{{ set_light_color_temp }}"
          - delay:
              milliseconds: 200
